-- Generated by tool/build_content.py. Do not edit by hand.
begin;
insert into grades (id, number, stage, stream, name) values ('g1', 1, 'lowerBasic', null, 'الصف الأول') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g1_arabic', 'g1', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g1_math', 'g1', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g1_science', 'g1', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g1_islamic', 'g1', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g1_english', 'g1', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g1_national', 'g1', 'national', 'التنشئة الوطنية والحياتية', 'flag', 4292617766, 5) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g2', 2, 'lowerBasic', null, 'الصف الثاني') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g2_arabic', 'g2', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g2_math', 'g2', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g2_science', 'g2', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g2_islamic', 'g2', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g2_english', 'g2', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g2_national', 'g2', 'national', 'التنشئة الوطنية والحياتية', 'flag', 4292617766, 5) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g3', 3, 'lowerBasic', null, 'الصف الثالث') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g3_arabic', 'g3', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g3_math', 'g3', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g3_science', 'g3', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g3_islamic', 'g3', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g3_english', 'g3', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g3_national', 'g3', 'national', 'التنشئة الوطنية والحياتية', 'flag', 4292617766, 5) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g4', 4, 'lowerBasic', null, 'الصف الرابع') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g4_arabic', 'g4', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g4_math', 'g4', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g4_science', 'g4', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g4_islamic', 'g4', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g4_english', 'g4', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g4_national', 'g4', 'national', 'التنشئة الوطنية والحياتية', 'flag', 4292617766, 5) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g5', 5, 'upperBasic', null, 'الصف الخامس') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g5_arabic', 'g5', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g5_math', 'g5', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g5_science', 'g5', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g5_islamic', 'g5', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g5_english', 'g5', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g5_social', 'g5', 'social', 'الدراسات الاجتماعية', 'public', 4290007817, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g5_tech', 'g5', 'tech', 'التكنولوجيا', 'computer', 4282865001, 6) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g6', 6, 'upperBasic', null, 'الصف السادس') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g6_arabic', 'g6', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g6_math', 'g6', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g6_science', 'g6', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g6_islamic', 'g6', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g6_english', 'g6', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g6_social', 'g6', 'social', 'الدراسات الاجتماعية', 'public', 4290007817, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g6_tech', 'g6', 'tech', 'التكنولوجيا', 'computer', 4282865001, 6) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g7', 7, 'upperBasic', null, 'الصف السابع') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g7_arabic', 'g7', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g7_math', 'g7', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g7_science', 'g7', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g7_islamic', 'g7', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g7_english', 'g7', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g7_social', 'g7', 'social', 'الدراسات الاجتماعية', 'public', 4290007817, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g7_tech', 'g7', 'tech', 'التكنولوجيا', 'computer', 4282865001, 6) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g8', 8, 'upperBasic', null, 'الصف الثامن') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g8_arabic', 'g8', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g8_math', 'g8', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g8_science', 'g8', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g8_islamic', 'g8', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g8_english', 'g8', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g8_social', 'g8', 'social', 'الدراسات الاجتماعية', 'public', 4290007817, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g8_tech', 'g8', 'tech', 'التكنولوجيا', 'computer', 4282865001, 6) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g9', 9, 'upperBasic', null, 'الصف التاسع') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g9_arabic', 'g9', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g9_math', 'g9', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g9_science', 'g9', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g9_islamic', 'g9', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g9_english', 'g9', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g9_social', 'g9', 'social', 'الدراسات الاجتماعية', 'public', 4290007817, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g9_tech', 'g9', 'tech', 'التكنولوجيا', 'computer', 4282865001, 6) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g10', 10, 'upperBasic', null, 'الصف العاشر') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g10_arabic', 'g10', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g10_math', 'g10', 'math', 'الرياضيات', 'calculate', 4280640491, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g10_science', 'g10', 'science', 'العلوم والحياة', 'science', 4279673674, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g10_islamic', 'g10', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g10_english', 'g10', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g10_social', 'g10', 'social', 'الدراسات الاجتماعية', 'public', 4290007817, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g10_tech', 'g10', 'tech', 'التكنولوجيا', 'computer', 4282865001, 6) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g11_sci', 11, 'secondary', 'علمي', 'الصف الحادي عشر') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_sci_arabic', 'g11_sci', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_sci_english', 'g11_sci', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_sci_islamic', 'g11_sci', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_sci_math', 'g11_sci', 'math', 'الرياضيات', 'calculate', 4280640491, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_sci_physics', 'g11_sci', 'physics', 'الفيزياء', 'bolt', 4293548044, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_sci_chemistry', 'g11_sci', 'chemistry', 'الكيمياء', 'biotech', 4278751666, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_sci_biology', 'g11_sci', 'biology', 'الأحياء', 'eco', 4279599165, 6) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_sci_tech', 'g11_sci', 'tech', 'التكنولوجيا', 'computer', 4282865001, 7) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g11_lit', 11, 'secondary', 'أدبي', 'الصف الحادي عشر') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_lit_arabic', 'g11_lit', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_lit_english', 'g11_lit', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_lit_islamic', 'g11_lit', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_lit_math', 'g11_lit', 'math', 'الرياضيات', 'calculate', 4280640491, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_lit_geography', 'g11_lit', 'geography', 'الجغرافيا', 'map', 4288766471, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_lit_history', 'g11_lit', 'history', 'التاريخ', 'history_edu', 4288614969, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g11_lit_tech', 'g11_lit', 'tech', 'التكنولوجيا', 'computer', 4282865001, 6) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g12_sci', 12, 'secondary', 'علمي', 'الصف الثاني عشر') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_sci_arabic', 'g12_sci', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_sci_english', 'g12_sci', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_sci_islamic', 'g12_sci', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_sci_math', 'g12_sci', 'math', 'الرياضيات', 'calculate', 4280640491, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_sci_physics', 'g12_sci', 'physics', 'الفيزياء', 'bolt', 4293548044, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_sci_chemistry', 'g12_sci', 'chemistry', 'الكيمياء', 'biotech', 4278751666, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_sci_biology', 'g12_sci', 'biology', 'الأحياء', 'eco', 4279599165, 6) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_sci_tech', 'g12_sci', 'tech', 'التكنولوجيا', 'computer', 4282865001, 7) on conflict (id) do nothing;
insert into grades (id, number, stage, stream, name) values ('g12_lit', 12, 'secondary', 'أدبي', 'الصف الثاني عشر') on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_lit_arabic', 'g12_lit', 'arabic', 'اللغة العربية', 'menu_book', 4279203438, 0) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_lit_english', 'g12_lit', 'english', 'اللغة الإنجليزية', 'translate', 4286331629, 1) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_lit_islamic', 'g12_lit', 'islamic', 'التربية الإسلامية', 'mosque', 4279080072, 2) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_lit_math', 'g12_lit', 'math', 'الرياضيات', 'calculate', 4280640491, 3) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_lit_geography', 'g12_lit', 'geography', 'الجغرافيا', 'map', 4288766471, 4) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_lit_history', 'g12_lit', 'history', 'التاريخ', 'history_edu', 4288614969, 5) on conflict (id) do nothing;
insert into subjects (id, grade_id, key, name, icon, color, sort) values ('g12_lit_tech', 'g12_lit', 'tech', 'التكنولوجيا', 'computer', 4282865001, 6) on conflict (id) do nothing;
insert into books (id, subject_id, title, pdf_url) values ('g4_math_book', 'g4_math', 'كتاب الرياضيات – الصف الرابع (نسخة تجريبية)', null) on conflict (id) do nothing;
insert into units (id, subject_id, semester, title, sort) values ('g4_math_u1', 'g4_math', 1, 'الوحدة الأولى: الكسور', 0) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g4_math_l1', 'g4_math_u1', 'مفهوم الكسر', array['أتعرّف معنى الكسر.','أميّز البسط والمقام.','أكتب كسرًا يعبّر عن شكل مقسّم إلى أجزاء متساوية.']::text[], 'الكسر هو جزء من كل مقسوم إلى أجزاء متساوية. نكتب الكسر بعددين بينهما خط:
• العدد في الأعلى يسمى البسط، ويدل على عدد الأجزاء التي أخذناها.
• العدد في الأسفل يسمى المقام، ويدل على عدد الأجزاء المتساوية التي قُسِّم إليها الكل.
مثلًا إذا قسمنا رغيفًا إلى 4 أجزاء متساوية وأكلنا جزءًا واحدًا، نكون قد أكلنا 1/4 (ربع) الرغيف.
شرط مهم: يجب أن تكون الأجزاء متساوية حتى نستطيع التعبير عنها بكسر.', array['قُسِّمت بيتزا إلى 8 قطع متساوية، أكل أحمد 3 قطع. الكسر الذي أكله: 3/8، البسط 3 والمقام 8.','في صف 5 تلاميذ، 2 منهم بنات. كسر البنات = 2/5.']::text[], array['البسط: عدد الأجزاء المأخوذة.','المقام: عدد الأجزاء المتساوية الكلي.','النصف = 1/2، الربع = 1/4، الثلث = 1/3.','الأجزاء يجب أن تكون متساوية.']::text[], 'الكسر يمثل جزءًا من كل مقسوم لأجزاء متساوية، ويُكتب على صورة بسط/مقام.', null, 3, 0, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q1', 'g4_math_l1', 'mcq', 1, 'في الكسر 3/5، ما هو البسط؟', array['5','3','8','2']::text[], '1'::jsonb, null, null, null, null, 'البسط هو العدد الموجود فوق خط الكسر وهو 3.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q2', 'g4_math_l1', 'trueFalse', 1, 'المقام هو العدد الموجود أسفل خط الكسر.', null, 'true'::jsonb, null, null, null, null, 'المقام يكتب أسفل الخط ويدل على عدد الأجزاء الكلي.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q3', 'g4_math_l1', 'fill', 1, 'في الكسر 2/7 يسمى العدد 7 ________.', null, null, array['المقام','مقام']::text[], null, null, null, 'العدد أسفل الخط هو المقام.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q4', 'g4_math_l1', 'mcq', 2, 'ما الكسر الذي يمثله الجزء الملوّن في الشكل؟', array['1/4','3/4','4/3','1/3']::text[], '1'::jsonb, null, null, null, null, 'الدائرة مقسمة إلى 4 أجزاء متساوية، لُوّن منها 3، فالكسر 3/4.', null, 'images/fraction_3_4.png', 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q5', 'g4_math_l1', 'numeric', 2, 'قُسِّمت كعكة إلى 8 أجزاء متساوية وأُكل منها 3 أجزاء. كم جزءًا بقي؟', null, '5'::jsonb, null, null, 0.001, null, 'عدد الأجزاء الباقية = 8 − 3 = 5.', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q6', 'g4_math_l1', 'match', 2, 'صِل كل كسر باسمه:', null, null, null, '[["1/2", "نصف"], ["1/4", "ربع"], ["1/3", "ثلث"]]'::jsonb, null, null, '1/2 نصف، 1/4 ربع، 1/3 ثلث.', null, null, 5) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q7', 'g4_math_l1', 'short', 3, 'اكتب الكسر الذي يعبّر عن جزأين من خمسة أجزاء متساوية.', null, null, array['2/5']::text[], null, null, null, 'عدد الأجزاء المأخوذة 2 (البسط) من أصل 5 (المقام): 2/5.', null, null, 6) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q8', 'g4_math_l1', 'trueFalse', 3, 'إذا قسمنا تفاحة إلى جزأين غير متساويين فإن كل جزء يساوي 1/2.', null, 'false'::jsonb, null, null, null, null, 'لا يكون الجزء نصفًا إلا إذا كان الجزآن متساويين.', null, null, 7) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l1_q9', 'g4_math_l1', 'essay', 3, 'اشرح بكلماتك لماذا يجب أن تكون الأجزاء متساوية عند كتابة كسر.', null, null, null, null, null, null, null, 'لأن الكسر يقارن الجزء بالكل، فإذا كانت الأجزاء مختلفة في الحجم لا يدل العدد نفسه على الكمية نفسها، فلا يمكن أن نقول إن كل جزء يساوي ربعًا مثلًا.', null, 8) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g4_math_l2', 'g4_math_u1', 'مقارنة الكسور', array['أقارن بين كسرين لهما المقام نفسه.','أقارن بين كسرين لهما البسط نفسه.']::text[], 'لمقارنة كسرين نستخدم القواعد التالية:
1) إذا تساوى المقامان: الكسر الأكبر هو صاحب البسط الأكبر، مثل 5/7 > 3/7.
2) إذا تساوى البسطان: الكسر الأكبر هو صاحب المقام الأصغر، مثل 1/3 > 1/5، لأن تقسيم الشيء إلى 3 أجزاء يعطي أجزاء أكبر من تقسيمه إلى 5 أجزاء.
نستخدم الرموز: > أكبر من، < أصغر من، = يساوي.', array['قارن بين 2/9 و 7/9: المقامان متساويان و 7 > 2، إذن 7/9 > 2/9.','قارن بين 3/4 و 3/8: البسطان متساويان والمقام 4 أصغر من 8، إذن 3/4 > 3/8.']::text[], array['المقامات متساوية ← نقارن البسوط.','البسوط متساوية ← المقام الأصغر يعني كسرًا أكبر.']::text[], 'عند تساوي المقامات نقارن البسوط، وعند تساوي البسوط فالمقام الأصغر يعطي الكسر الأكبر.', null, 5, 1, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l2_q1', 'g4_math_l2', 'mcq', 1, 'أيّ الكسرين أكبر: 4/9 أم 7/9؟', array['4/9','7/9','متساويان']::text[], '1'::jsonb, null, null, null, null, 'المقامان متساويان، و7 أكبر من 4.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l2_q2', 'g4_math_l2', 'trueFalse', 1, '1/2 أكبر من 1/4.', null, 'true'::jsonb, null, null, null, null, 'البسطان متساويان والمقام 2 أصغر من 4، فالنصف أكبر.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l2_q3', 'g4_math_l2', 'mcq', 2, 'اختر الرمز المناسب: 3/5 ___ 3/8', array['>','<','=']::text[], '0'::jsonb, null, null, null, null, 'المقام 5 أصغر من 8، إذن 3/5 > 3/8.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l2_q4', 'g4_math_l2', 'fill', 2, 'إذا تساوت مقامات الكسور فإن الكسر الأكبر هو صاحب ________ الأكبر.', null, null, array['البسط','بسط']::text[], null, null, null, 'عند تساوي المقامات نقارن البسوط.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l2_q5', 'g4_math_l2', 'mcq', 3, 'رتّب الكسور من الأصغر إلى الأكبر: 1/3، 1/6، 1/2', array['1/2، 1/3، 1/6','1/6، 1/3، 1/2','1/3، 1/6، 1/2']::text[], '1'::jsonb, null, null, null, null, 'البسوط متساوية، فالمقام الأكبر يعني الكسر الأصغر: 1/6 < 1/3 < 1/2.', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l2_q6', 'g4_math_l2', 'trueFalse', 3, 'أكلت سارة 2/8 من فطيرة وأكلت ليلى 2/4 من فطيرة مماثلة، إذن أكلت سارة أكثر.', null, 'false'::jsonb, null, null, null, null, '2/4 أكبر من 2/8 لأن المقام 4 أصغر، إذن ليلى أكلت أكثر.', null, null, 5) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l2_q7', 'g4_math_l2', 'short', 4, 'اكتب كسرًا مقامه 10 ويكون أكبر من 7/10 وأصغر من 9/10.', null, null, array['8/10','4/5']::text[], null, null, null, 'الكسر الوحيد بمقام 10 بينهما هو 8/10.', null, null, 6) on conflict (id) do nothing;
insert into units (id, subject_id, semester, title, sort) values ('g4_math_u2', 'g4_math', 2, 'الوحدة الثانية: القياس', 1) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g4_math_l3', 'g4_math_u2', 'محيط المستطيل والمربع', array['أتعرّف مفهوم المحيط.','أحسب محيط المستطيل والمربع.']::text[], 'المحيط هو طول الخط الذي يحيط بالشكل، أي مجموع أطوال أضلاعه.
• محيط المستطيل = (الطول + العرض) × 2.
• محيط المربع = طول الضلع × 4، لأن أضلاعه الأربعة متساوية.
يقاس المحيط بوحدات الطول مثل السنتيمتر (سم) والمتر (م).', array['مستطيل طوله 6 سم وعرضه 4 سم: المحيط = (6 + 4) × 2 = 20 سم.','مربع طول ضلعه 5 م: المحيط = 5 × 4 = 20 م.']::text[], array['المحيط = مجموع أطوال الأضلاع.','محيط المستطيل = (الطول + العرض) × 2.','محيط المربع = الضلع × 4.']::text[], 'نحسب المحيط بجمع أطوال الأضلاع، وللمستطيل (الطول + العرض) × 2 وللمربع الضلع × 4.', null, 8, 0, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l3_q1', 'g4_math_l3', 'numeric', 1, 'مربع طول ضلعه 3 سم. ما محيطه؟', null, '12'::jsonb, null, null, 0.001, 'سم', 'المحيط = 3 × 4 = 12 سم.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l3_q2', 'g4_math_l3', 'numeric', 2, 'مستطيل طوله 7 سم وعرضه 3 سم. ما محيطه؟', null, '20'::jsonb, null, null, 0.001, 'سم', 'المحيط = (7 + 3) × 2 = 20 سم.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l3_q3', 'g4_math_l3', 'trueFalse', 1, 'يقاس المحيط بوحدة السنتيمتر المربع.', null, 'false'::jsonb, null, null, null, null, 'المحيط طول، فيقاس بالسنتيمتر وليس بالسنتيمتر المربع.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l3_q4', 'g4_math_l3', 'mcq', 2, 'أيّ القوانين التالية يحسب محيط المستطيل؟', array['الطول × العرض','(الطول + العرض) × 2','الطول + العرض','الضلع × 4']::text[], '1'::jsonb, null, null, null, null, 'نجمع الطول والعرض ثم نضرب في 2.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l3_q5', 'g4_math_l3', 'numeric', 3, 'حديقة مربعة الشكل محيطها 36 مترًا. ما طول ضلعها؟', null, '9'::jsonb, null, null, 0.001, 'م', 'طول الضلع = 36 ÷ 4 = 9 م.', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_math_l3_q6', 'g4_math_l3', 'numeric', 4, 'مستطيل محيطه 30 سم وطوله 10 سم. ما عرضه؟', null, '5'::jsonb, null, null, 0.001, 'سم', 'نصف المحيط = 15 = الطول + العرض، إذن العرض = 15 − 10 = 5 سم.', null, null, 5) on conflict (id) do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 1, 'كتاب الرياضيات – الصف الرابع (نسخة تجريبية)

المحتويات:
• الوحدة الأولى: الكسور
• الوحدة الثانية: القياس', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 2, 'الوحدة الأولى: الكسور', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 3, 'مفهوم الكسر

الكسر هو جزء من كل مقسوم إلى أجزاء متساوية. نكتب الكسر بعددين بينهما خط:
• العدد في الأعلى يسمى البسط، ويدل على عدد الأجزاء التي أخذناها.
• العدد في الأسفل يسمى المقام، ويدل على عدد الأجزاء المتساوية التي قُسِّم إليها الكل.
مثلًا إذا قسمنا رغيفًا إلى 4 أجزاء متساوية وأكلنا جزءًا واحدًا، نكون قد أكلنا 1/4 (ربع) الرغيف.
شرط مهم: يجب أن تكون الأجزاء متساوية حتى نستطيع التعبير عنها بكسر.', 'g4_math_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 4, 'أمثلة محلولة:
• قُسِّمت بيتزا إلى 8 قطع متساوية، أكل أحمد 3 قطع. الكسر الذي أكله: 3/8، البسط 3 والمقام 8.
• في صف 5 تلاميذ، 2 منهم بنات. كسر البنات = 2/5.

أتذكّر:
• البسط: عدد الأجزاء المأخوذة.
• المقام: عدد الأجزاء المتساوية الكلي.
• النصف = 1/2، الربع = 1/4، الثلث = 1/3.
• الأجزاء يجب أن تكون متساوية.', 'g4_math_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 5, 'مقارنة الكسور

لمقارنة كسرين نستخدم القواعد التالية:
1) إذا تساوى المقامان: الكسر الأكبر هو صاحب البسط الأكبر، مثل 5/7 > 3/7.
2) إذا تساوى البسطان: الكسر الأكبر هو صاحب المقام الأصغر، مثل 1/3 > 1/5، لأن تقسيم الشيء إلى 3 أجزاء يعطي أجزاء أكبر من تقسيمه إلى 5 أجزاء.
نستخدم الرموز: > أكبر من، < أصغر من، = يساوي.', 'g4_math_l2') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 6, 'أمثلة محلولة:
• قارن بين 2/9 و 7/9: المقامان متساويان و 7 > 2، إذن 7/9 > 2/9.
• قارن بين 3/4 و 3/8: البسطان متساويان والمقام 4 أصغر من 8، إذن 3/4 > 3/8.

أتذكّر:
• المقامات متساوية ← نقارن البسوط.
• البسوط متساوية ← المقام الأصغر يعني كسرًا أكبر.', 'g4_math_l2') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 7, 'الوحدة الثانية: القياس', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 8, 'محيط المستطيل والمربع

المحيط هو طول الخط الذي يحيط بالشكل، أي مجموع أطوال أضلاعه.
• محيط المستطيل = (الطول + العرض) × 2.
• محيط المربع = طول الضلع × 4، لأن أضلاعه الأربعة متساوية.
يقاس المحيط بوحدات الطول مثل السنتيمتر (سم) والمتر (م).', 'g4_math_l3') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_math_book', 9, 'أمثلة محلولة:
• مستطيل طوله 6 سم وعرضه 4 سم: المحيط = (6 + 4) × 2 = 20 سم.
• مربع طول ضلعه 5 م: المحيط = 5 × 4 = 20 م.

أتذكّر:
• المحيط = مجموع أطوال الأضلاع.
• محيط المستطيل = (الطول + العرض) × 2.
• محيط المربع = الضلع × 4.', 'g4_math_l3') on conflict do nothing;
insert into exams (id, subject_id, title, duration_minutes, question_count) values ('g4_math_exam1', 'g4_math', 'امتحان تجريبي – الرياضيات', 20, 10) on conflict (id) do nothing;
insert into books (id, subject_id, title, pdf_url) values ('g4_science_book', 'g4_science', 'كتاب العلوم والحياة – الصف الرابع (نسخة تجريبية)', null) on conflict (id) do nothing;
insert into units (id, subject_id, semester, title, sort) values ('g4_science_u1', 'g4_science', 1, 'الوحدة الأولى: النبات', 0) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g4_science_l1', 'g4_science_u1', 'أجزاء النبات ووظائفها', array['أسمّي أجزاء النبات الرئيسية.','أذكر وظيفة كل جزء.']::text[], 'يتكون النبات الزهري من أجزاء رئيسية لكل منها وظيفة:
• الجذر: يثبّت النبات في التربة ويمتص الماء والأملاح منها.
• الساق: تحمل الأوراق والأزهار، وتنقل الماء من الجذر إلى باقي النبات.
• الأوراق: تصنع الغذاء للنبات بوجود ضوء الشمس، وتسمى هذه العملية البناء الضوئي.
• الزهرة: مسؤولة عن التكاثر، ومنها تتكون الثمار والبذور.', array['عندما نسقي شجرة الليمون يمتص جذرها الماء، ثم تنقله الساق إلى الأوراق.','زهرة شجرة البرتقال تتحول إلى ثمرة برتقال بداخلها بذور.']::text[], array['الجذر: تثبيت وامتصاص.','الساق: حمل ونقل.','الورقة: صنع الغذاء.','الزهرة: التكاثر.']::text[], 'أجزاء النبات أربعة رئيسية: الجذر والساق والأوراق والزهرة، ولكل منها وظيفة تحافظ على حياة النبات.', null, 3, 0, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l1_q1', 'g4_science_l1', 'mcq', 1, 'ما الجزء الذي يمتص الماء من التربة؟', array['الورقة','الزهرة','الجذر','الثمرة']::text[], '2'::jsonb, null, null, null, null, 'الجذر يمتص الماء والأملاح من التربة.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l1_q2', 'g4_science_l1', 'trueFalse', 1, 'الأوراق هي الجزء الذي يصنع الغذاء للنبات.', null, 'true'::jsonb, null, null, null, null, 'تصنع الأوراق الغذاء بعملية البناء الضوئي.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l1_q3', 'g4_science_l1', 'match', 2, 'صِل كل جزء بوظيفته:', null, null, null, '[["الجذر", "يثبّت النبات"], ["الساق", "تنقل الماء"], ["الزهرة", "التكاثر"]]'::jsonb, null, null, 'الجذر للتثبيت، الساق للنقل، الزهرة للتكاثر.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l1_q4', 'g4_science_l1', 'fill', 2, 'تسمى عملية صنع الغذاء في الأوراق بعملية البناء ________.', null, null, array['الضوئي','ضوئي']::text[], null, null, null, 'البناء الضوئي يحتاج ضوء الشمس.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l1_q5', 'g4_science_l1', 'mcq', 3, 'إذا قُطعت ساق نبتة صغيرة من منتصفها، فماذا يحدث للأوراق العليا غالبًا؟', array['تنمو أسرع','تذبل لأن الماء لا يصلها','تتحول إلى أزهار']::text[], '1'::jsonb, null, null, null, null, 'الساق تنقل الماء، فإذا قطعت لا يصل الماء للأوراق فتذبل.', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l1_q6', 'g4_science_l1', 'essay', 3, 'لماذا لا تستطيع النبتة العيش طويلًا بلا جذور؟', null, null, null, null, null, null, null, 'لأن الجذور تثبتها في التربة وتمتص الماء والأملاح، وبدونها لا يصل الماء إلى الساق والأوراق فتذبل وتموت.', null, 5) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g4_science_l2', 'g4_science_u1', 'حاجات النبات', array['أذكر ما يحتاجه النبات لينمو.','أصمم تجربة بسيطة تبيّن أهمية الضوء.']::text[], 'يحتاج النبات إلى عدة أشياء لينمو بشكل سليم:
• الماء: يمتصه من التربة عبر الجذور.
• ضوء الشمس: تستخدمه الأوراق لصنع الغذاء.
• الهواء: يأخذ منه ثاني أكسيد الكربون لصنع الغذاء.
• التربة: يثبت فيها ويحصل منها على الأملاح المعدنية.
تجربة: ضع نبتتين متشابهتين، واحدة في الضوء وأخرى في خزانة مظلمة، واسقهما بالماء نفسه. بعد أسبوع تصفرّ النبتة المظلمة وتضعف.', array['النبتة الموضوعة قرب النافذة تميل نحو الضوء.','نبتة لم تُسقَ أسبوعين تذبل أوراقها.']::text[], array['الماء والضوء والهواء والتربة حاجات أساسية.','الضوء ضروري لصنع الغذاء.']::text[], 'ينمو النبات عند توفر الماء والضوء والهواء والتربة، وغياب أحدها يضعف النبات.', null, 5, 1, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l2_q1', 'g4_science_l2', 'mcq', 1, 'أيّ مما يلي ليس من حاجات النبات الأساسية؟', array['الماء','الضوء','الصوت','الهواء']::text[], '2'::jsonb, null, null, null, null, 'الصوت ليس من الحاجات الأساسية للنبات.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l2_q2', 'g4_science_l2', 'trueFalse', 1, 'تستطيع النباتات الخضراء صنع غذائها في الظلام الدامس.', null, 'false'::jsonb, null, null, null, null, 'تحتاج الأوراق إلى الضوء لصنع الغذاء.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l2_q3', 'g4_science_l2', 'fill', 2, 'يأخذ النبات من الهواء غاز ثاني أكسيد ________.', null, null, array['الكربون','كربون']::text[], null, null, null, 'يستخدم النبات ثاني أكسيد الكربون في صنع الغذاء.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l2_q4', 'g4_science_l2', 'mcq', 2, 'وُضعت نبتة في خزانة مظلمة أسبوعًا. ماذا تتوقع؟', array['تصبح أكثر خضرة','تصفرّ وتضعف','لا تتغير أبدًا']::text[], '1'::jsonb, null, null, null, null, 'غياب الضوء يمنع صنع الغذاء فتضعف.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_science_l2_q5', 'g4_science_l2', 'essay', 3, 'صف تجربة تبيّن أن النبات يحتاج إلى الماء.', null, null, null, null, null, null, null, 'نأخذ نبتتين متشابهتين في الظروف نفسها من ضوء وهواء، نسقي الأولى ولا نسقي الثانية، وبعد أيام نلاحظ أن النبتة التي لم تُسقَ ذبلت، فنستنتج أن الماء ضروري.', null, 4) on conflict (id) do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_science_book', 1, 'كتاب العلوم والحياة – الصف الرابع (نسخة تجريبية)

المحتويات:
• الوحدة الأولى: النبات', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_science_book', 2, 'الوحدة الأولى: النبات', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_science_book', 3, 'أجزاء النبات ووظائفها

يتكون النبات الزهري من أجزاء رئيسية لكل منها وظيفة:
• الجذر: يثبّت النبات في التربة ويمتص الماء والأملاح منها.
• الساق: تحمل الأوراق والأزهار، وتنقل الماء من الجذر إلى باقي النبات.
• الأوراق: تصنع الغذاء للنبات بوجود ضوء الشمس، وتسمى هذه العملية البناء الضوئي.
• الزهرة: مسؤولة عن التكاثر، ومنها تتكون الثمار والبذور.', 'g4_science_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_science_book', 4, 'أمثلة محلولة:
• عندما نسقي شجرة الليمون يمتص جذرها الماء، ثم تنقله الساق إلى الأوراق.
• زهرة شجرة البرتقال تتحول إلى ثمرة برتقال بداخلها بذور.

أتذكّر:
• الجذر: تثبيت وامتصاص.
• الساق: حمل ونقل.
• الورقة: صنع الغذاء.
• الزهرة: التكاثر.', 'g4_science_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_science_book', 5, 'حاجات النبات

يحتاج النبات إلى عدة أشياء لينمو بشكل سليم:
• الماء: يمتصه من التربة عبر الجذور.
• ضوء الشمس: تستخدمه الأوراق لصنع الغذاء.
• الهواء: يأخذ منه ثاني أكسيد الكربون لصنع الغذاء.
• التربة: يثبت فيها ويحصل منها على الأملاح المعدنية.
تجربة: ضع نبتتين متشابهتين، واحدة في الضوء وأخرى في خزانة مظلمة، واسقهما بالماء نفسه. بعد أسبوع تصفرّ النبتة المظلمة وتضعف.', 'g4_science_l2') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_science_book', 6, 'أمثلة محلولة:
• النبتة الموضوعة قرب النافذة تميل نحو الضوء.
• نبتة لم تُسقَ أسبوعين تذبل أوراقها.

أتذكّر:
• الماء والضوء والهواء والتربة حاجات أساسية.
• الضوء ضروري لصنع الغذاء.', 'g4_science_l2') on conflict do nothing;
insert into exams (id, subject_id, title, duration_minutes, question_count) values ('g4_science_exam1', 'g4_science', 'امتحان تجريبي – العلوم', 15, 8) on conflict (id) do nothing;
insert into books (id, subject_id, title, pdf_url) values ('g4_arabic_book', 'g4_arabic', 'كتاب اللغة العربية – الصف الرابع (نسخة تجريبية)', null) on conflict (id) do nothing;
insert into units (id, subject_id, semester, title, sort) values ('g4_arabic_u1', 'g4_arabic', 1, 'الوحدة الأولى: قواعد اللغة', 0) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g4_arabic_l1', 'g4_arabic_u1', 'الجملة الاسمية والجملة الفعلية', array['أميّز الجملة الاسمية من الجملة الفعلية.','أكوّن جملًا اسمية وفعلية.']::text[], 'تنقسم الجملة في اللغة العربية إلى نوعين:
• الجملة الاسمية: هي التي تبدأ باسم، وتتكون من مبتدأ وخبر. مثل: «الشمسُ مشرقةٌ».
• الجملة الفعلية: هي التي تبدأ بفعل، وتتكون من فعل وفاعل. مثل: «ذهبَ الطالبُ إلى المدرسة».
لمعرفة نوع الجملة ننظر إلى أول كلمة فيها: إن كانت اسمًا فهي اسمية، وإن كانت فعلًا فهي فعلية.', array['«غزةُ جميلةٌ»: تبدأ باسم (غزة) فهي جملة اسمية.','«يقرأُ أحمدُ القصةَ»: تبدأ بفعل (يقرأ) فهي جملة فعلية.']::text[], array['الجملة الاسمية تبدأ باسم: مبتدأ + خبر.','الجملة الفعلية تبدأ بفعل: فعل + فاعل.','ننظر إلى الكلمة الأولى لتحديد النوع.']::text[], 'الجملة الاسمية تبدأ باسم والجملة الفعلية تبدأ بفعل.', null, 3, 0, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_arabic_l1_q1', 'g4_arabic_l1', 'mcq', 1, 'ما نوع جملة: «البحرُ واسعٌ»؟', array['جملة اسمية','جملة فعلية']::text[], '0'::jsonb, null, null, null, null, 'تبدأ باسم (البحر).', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_arabic_l1_q2', 'g4_arabic_l1', 'mcq', 1, 'ما نوع جملة: «لعبَ الأطفالُ في الحديقة»؟', array['جملة اسمية','جملة فعلية']::text[], '1'::jsonb, null, null, null, null, 'تبدأ بفعل (لعب).', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_arabic_l1_q3', 'g4_arabic_l1', 'trueFalse', 1, 'تتكون الجملة الاسمية من فعل وفاعل.', null, 'false'::jsonb, null, null, null, null, 'الجملة الاسمية تتكون من مبتدأ وخبر.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_arabic_l1_q4', 'g4_arabic_l1', 'fill', 2, 'تتكون الجملة الاسمية من مبتدأ و________.', null, null, array['خبر','الخبر']::text[], null, null, null, 'ركنا الجملة الاسمية: المبتدأ والخبر.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_arabic_l1_q5', 'g4_arabic_l1', 'match', 2, 'صِل كل جملة بنوعها:', null, null, null, '[["المعلمُ نشيطٌ", "اسمية"], ["كتبَ الطالبُ الدرسَ", "فعلية"]]'::jsonb, null, null, 'الأولى تبدأ باسم والثانية تبدأ بفعل.', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g4_arabic_l1_q6', 'g4_arabic_l1', 'short', 3, 'حوّل الجملة «يزرعُ الفلاحُ الزيتونَ» إلى جملة اسمية.', null, null, array['الفلاح يزرع الزيتون','الفلاحُ يزرعُ الزيتونَ']::text[], null, null, null, 'نبدأ بالاسم: الفلاحُ يزرعُ الزيتونَ.', null, null, 5) on conflict (id) do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_arabic_book', 1, 'كتاب اللغة العربية – الصف الرابع (نسخة تجريبية)

المحتويات:
• الوحدة الأولى: قواعد اللغة', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_arabic_book', 2, 'الوحدة الأولى: قواعد اللغة', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_arabic_book', 3, 'الجملة الاسمية والجملة الفعلية

تنقسم الجملة في اللغة العربية إلى نوعين:
• الجملة الاسمية: هي التي تبدأ باسم، وتتكون من مبتدأ وخبر. مثل: «الشمسُ مشرقةٌ».
• الجملة الفعلية: هي التي تبدأ بفعل، وتتكون من فعل وفاعل. مثل: «ذهبَ الطالبُ إلى المدرسة».
لمعرفة نوع الجملة ننظر إلى أول كلمة فيها: إن كانت اسمًا فهي اسمية، وإن كانت فعلًا فهي فعلية.', 'g4_arabic_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g4_arabic_book', 4, 'أمثلة محلولة:
• «غزةُ جميلةٌ»: تبدأ باسم (غزة) فهي جملة اسمية.
• «يقرأُ أحمدُ القصةَ»: تبدأ بفعل (يقرأ) فهي جملة فعلية.

أتذكّر:
• الجملة الاسمية تبدأ باسم: مبتدأ + خبر.
• الجملة الفعلية تبدأ بفعل: فعل + فاعل.
• ننظر إلى الكلمة الأولى لتحديد النوع.', 'g4_arabic_l1') on conflict do nothing;
insert into books (id, subject_id, title, pdf_url) values ('g9_math_book', 'g9_math', 'كتاب الرياضيات – الصف التاسع (نسخة تجريبية)', null) on conflict (id) do nothing;
insert into units (id, subject_id, semester, title, sort) values ('g9_math_u1', 'g9_math', 1, 'الوحدة الأولى: المعادلات', 0) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g9_math_l1', 'g9_math_u1', 'حل المعادلات الخطية بمتغير واحد', array['أحل معادلة خطية بمتغير واحد.','أتحقق من صحة الحل بالتعويض.']::text[], 'المعادلة الخطية بمتغير واحد على الصورة: أ س + ب = جـ، حيث أ ≠ 0.
لحلها نعزل المتغير س في طرف واحد باستخدام العمليات العكسية، مع إجراء العملية نفسها على الطرفين:
1) نطرح (أو نجمع) الحد الثابت من الطرفين.
2) نقسم الطرفين على معامل س.
3) نتحقق بتعويض قيمة س في المعادلة الأصلية.', array['حل المعادلة 2س + 3 = 11: نطرح 3 ← 2س = 8، نقسم على 2 ← س = 4. التحقق: 2(4) + 3 = 11 ✓','حل المعادلة 5س − 7 = 3س + 9: ننقل الحدود ← 2س = 16 ← س = 8.']::text[], array['ما نفعله في طرف نفعله في الطرف الآخر.','نستخدم العمليات العكسية لعزل المتغير.','نتحقق دائمًا بالتعويض.']::text[], 'نحل المعادلة الخطية بعزل المتغير باستخدام العمليات العكسية على الطرفين ثم نتحقق بالتعويض.', null, 3, 0, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l1_q1', 'g9_math_l1', 'numeric', 1, 'حل المعادلة: س + 7 = 12. ما قيمة س؟', null, '5'::jsonb, null, null, 0.001, null, 'س = 12 − 7 = 5.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l1_q2', 'g9_math_l1', 'numeric', 1, 'حل المعادلة: 3س = 21. ما قيمة س؟', null, '7'::jsonb, null, null, 0.001, null, 'س = 21 ÷ 3 = 7.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l1_q3', 'g9_math_l1', 'numeric', 2, 'حل المعادلة: 2س + 3 = 11. ما قيمة س؟', null, '4'::jsonb, null, null, 0.001, null, '2س = 8 ← س = 4.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l1_q4', 'g9_math_l1', 'mcq', 2, 'ما الخطوة الأولى المناسبة لحل 4س − 5 = 15؟', array['قسمة الطرفين على 4','جمع 5 إلى الطرفين','طرح 15 من الطرفين']::text[], '1'::jsonb, null, null, null, null, 'نتخلص من الحد الثابت أولًا بجمع 5: 4س = 20.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l1_q5', 'g9_math_l1', 'trueFalse', 2, 'س = 3 حل للمعادلة 5س − 4 = 11.', null, 'true'::jsonb, null, null, null, null, '5(3) − 4 = 15 − 4 = 11 ✓', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l1_q6', 'g9_math_l1', 'numeric', 3, 'حل المعادلة: 5س − 7 = 3س + 9. ما قيمة س؟', null, '8'::jsonb, null, null, 0.001, null, '2س = 16 ← س = 8.', null, null, 5) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l1_q7', 'g9_math_l1', 'numeric', 4, 'عمر أحمد الآن س سنة، وبعد 6 سنوات يصبح عمره ضعف عمره قبل سنة واحدة. ما قيمة س؟', null, '8'::jsonb, null, null, 0.001, null, 'س + 6 = 2(س − 1) ← س + 6 = 2س − 2 ← س = 8.', null, null, 6) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l1_q8', 'g9_math_l1', 'essay', 3, 'اشرح لماذا يجب إجراء العملية نفسها على طرفي المعادلة.', null, null, null, null, null, null, null, 'لأن المعادلة تمثل توازنًا بين طرفين متساويين، وإجراء العملية نفسها على الطرفين يحافظ على التساوي.', null, 7) on conflict (id) do nothing;
insert into units (id, subject_id, semester, title, sort) values ('g9_math_u2', 'g9_math', 2, 'الوحدة الثانية: الهندسة', 1) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g9_math_l2', 'g9_math_u2', 'نظرية فيثاغورس', array['أتعرّف نظرية فيثاغورس.','أحسب طول ضلع مجهول في مثلث قائم الزاوية.']::text[], 'في المثلث القائم الزاوية يسمى الضلع المقابل للزاوية القائمة «الوتر»، وهو أطول الأضلاع.
تنص نظرية فيثاغورس على أن: مربع طول الوتر = مجموع مربعي طولي الضلعين الآخرين.
أي: جـ² = أ² + ب²، حيث جـ الوتر.
ويمكن استخدام عكس النظرية لمعرفة هل المثلث قائم الزاوية أم لا.', array['مثلث قائم ضلعاه 3 سم و 4 سم: جـ² = 9 + 16 = 25 ← جـ = 5 سم.','مثلث قائم وتره 13 وأحد ضلعيه 5: ب² = 169 − 25 = 144 ← ب = 12.']::text[], array['الوتر يقابل الزاوية القائمة وهو الأطول.','جـ² = أ² + ب².','الأعداد 3، 4، 5 ثلاثية فيثاغورسية.']::text[], 'في المثلث القائم: مربع الوتر يساوي مجموع مربعي الضلعين الآخرين.', null, 6, 0, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l2_q1', 'g9_math_l2', 'trueFalse', 1, 'الوتر هو أطول أضلاع المثلث القائم الزاوية.', null, 'true'::jsonb, null, null, null, null, 'الوتر يقابل الزاوية القائمة وهي أكبر زاوية.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l2_q2', 'g9_math_l2', 'numeric', 2, 'مثلث قائم الزاوية طولا ضلعيه 6 سم و 8 سم. ما طول الوتر؟', null, '10'::jsonb, null, null, 0.001, 'سم', 'جـ² = 36 + 64 = 100 ← جـ = 10 سم.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l2_q3', 'g9_math_l2', 'numeric', 2, 'مثلث قائم الزاوية وتره 13 سم وأحد ضلعيه 5 سم. ما طول الضلع الآخر؟', null, '12'::jsonb, null, null, 0.001, 'سم', 'ب² = 169 − 25 = 144 ← ب = 12 سم.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l2_q4', 'g9_math_l2', 'mcq', 2, 'في المثلث القائم المرسوم: الضلع الرأسي 3 وحدات والقاعدة 4 وحدات (كل علامة زرقاء تفصل وحدة). ما طول الوتر الملوّن بالأحمر؟', array['7','5','12','25']::text[], '1'::jsonb, null, null, null, null, 'جـ² = 3² + 4² = 25 ← جـ = 5.', null, 'images/right_triangle.png', 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l2_q5', 'g9_math_l2', 'mcq', 3, 'أيّ الثلاثيات التالية يمكن أن تكون أطوال أضلاع مثلث قائم؟', array['4، 5، 6','5، 12، 13','2، 3، 4','6، 7، 9']::text[], '1'::jsonb, null, null, null, null, '25 + 144 = 169 = 13².', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_math_l2_q6', 'g9_math_l2', 'numeric', 4, 'سلّم طوله 10 أمتار يستند إلى جدار، وبُعد أسفله عن الجدار 6 أمتار. على أي ارتفاع يلامس الجدار؟', null, '8'::jsonb, null, null, 0.001, 'م', 'الارتفاع² = 100 − 36 = 64 ← الارتفاع = 8 م.', null, null, 5) on conflict (id) do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_math_book', 1, 'كتاب الرياضيات – الصف التاسع (نسخة تجريبية)

المحتويات:
• الوحدة الأولى: المعادلات
• الوحدة الثانية: الهندسة', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_math_book', 2, 'الوحدة الأولى: المعادلات', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_math_book', 3, 'حل المعادلات الخطية بمتغير واحد

المعادلة الخطية بمتغير واحد على الصورة: أ س + ب = جـ، حيث أ ≠ 0.
لحلها نعزل المتغير س في طرف واحد باستخدام العمليات العكسية، مع إجراء العملية نفسها على الطرفين:
1) نطرح (أو نجمع) الحد الثابت من الطرفين.
2) نقسم الطرفين على معامل س.
3) نتحقق بتعويض قيمة س في المعادلة الأصلية.', 'g9_math_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_math_book', 4, 'أمثلة محلولة:
• حل المعادلة 2س + 3 = 11: نطرح 3 ← 2س = 8، نقسم على 2 ← س = 4. التحقق: 2(4) + 3 = 11 ✓
• حل المعادلة 5س − 7 = 3س + 9: ننقل الحدود ← 2س = 16 ← س = 8.

أتذكّر:
• ما نفعله في طرف نفعله في الطرف الآخر.
• نستخدم العمليات العكسية لعزل المتغير.
• نتحقق دائمًا بالتعويض.', 'g9_math_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_math_book', 5, 'الوحدة الثانية: الهندسة', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_math_book', 6, 'نظرية فيثاغورس

في المثلث القائم الزاوية يسمى الضلع المقابل للزاوية القائمة «الوتر»، وهو أطول الأضلاع.
تنص نظرية فيثاغورس على أن: مربع طول الوتر = مجموع مربعي طولي الضلعين الآخرين.
أي: جـ² = أ² + ب²، حيث جـ الوتر.
ويمكن استخدام عكس النظرية لمعرفة هل المثلث قائم الزاوية أم لا.', 'g9_math_l2') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_math_book', 7, 'أمثلة محلولة:
• مثلث قائم ضلعاه 3 سم و 4 سم: جـ² = 9 + 16 = 25 ← جـ = 5 سم.
• مثلث قائم وتره 13 وأحد ضلعيه 5: ب² = 169 − 25 = 144 ← ب = 12.

أتذكّر:
• الوتر يقابل الزاوية القائمة وهو الأطول.
• جـ² = أ² + ب².
• الأعداد 3، 4، 5 ثلاثية فيثاغورسية.', 'g9_math_l2') on conflict do nothing;
insert into exams (id, subject_id, title, duration_minutes, question_count) values ('g9_math_exam1', 'g9_math', 'امتحان تجريبي – الرياضيات', 30, 10) on conflict (id) do nothing;
insert into books (id, subject_id, title, pdf_url) values ('g9_science_book', 'g9_science', 'كتاب العلوم – الصف التاسع (نسخة تجريبية)', null) on conflict (id) do nothing;
insert into units (id, subject_id, semester, title, sort) values ('g9_science_u1', 'g9_science', 1, 'الوحدة الأولى: القوة والحركة', 0) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g9_science_l1', 'g9_science_u1', 'قانون نيوتن الأول (القصور الذاتي)', array['أنص على قانون نيوتن الأول.','أفسّر مواقف حياتية باستخدام مفهوم القصور الذاتي.']::text[], 'ينص قانون نيوتن الأول على أن: الجسم الساكن يبقى ساكنًا، والجسم المتحرك يبقى متحركًا بسرعة ثابتة وفي خط مستقيم، ما لم تؤثر فيه قوة محصلة تغيّر حالته.
تسمى ممانعة الجسم لتغيير حالته الحركية «القصور الذاتي»، ويزداد القصور الذاتي بزيادة كتلة الجسم.
لذلك يندفع الركاب إلى الأمام عند توقف الحافلة فجأة، ولهذا نستخدم حزام الأمان.', array['عند توقف السيارة فجأة يندفع جسم الراكب إلى الأمام لأنه يميل إلى الاستمرار في حركته.','سحب مفرش الطاولة بسرعة يبقي الأطباق في مكانها تقريبًا بسبب قصورها الذاتي.']::text[], array['لا يغيّر الجسم حالته الحركية إلا بقوة محصلة.','القصور الذاتي يزداد بزيادة الكتلة.','حزام الأمان تطبيق على القانون الأول.']::text[], 'يحافظ الجسم على حالته من سكون أو حركة منتظمة ما لم تؤثر فيه قوة محصلة، وهذا هو القصور الذاتي.', null, 3, 0, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l1_q1', 'g9_science_l1', 'trueFalse', 1, 'الجسم الساكن يبقى ساكنًا ما لم تؤثر فيه قوة محصلة.', null, 'true'::jsonb, null, null, null, null, 'هذا نص قانون نيوتن الأول.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l1_q2', 'g9_science_l1', 'mcq', 1, 'يسمى ميل الجسم إلى مقاومة التغير في حالته الحركية:', array['التسارع','القصور الذاتي','الوزن','الاحتكاك']::text[], '1'::jsonb, null, null, null, null, 'هذا تعريف القصور الذاتي.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l1_q3', 'g9_science_l1', 'mcq', 2, 'لماذا يندفع الركاب إلى الأمام عند توقف الحافلة فجأة؟', array['بسبب قوة تدفعهم للأمام','لأن أجسامهم تميل للاستمرار في الحركة','بسبب الجاذبية']::text[], '1'::jsonb, null, null, null, null, 'بسبب القصور الذاتي تستمر أجسامهم في الحركة.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l1_q4', 'g9_science_l1', 'mcq', 2, 'أيّ الجسمين قصوره الذاتي أكبر؟', array['دراجة هوائية','شاحنة محمّلة']::text[], '1'::jsonb, null, null, null, null, 'الشاحنة كتلتها أكبر فقصورها الذاتي أكبر.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l1_q5', 'g9_science_l1', 'fill', 3, 'يزداد القصور الذاتي للجسم بزيادة ________.', null, null, array['كتلته','الكتلة','كتلة']::text[], null, null, null, 'القصور الذاتي مرتبط بالكتلة.', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l1_q6', 'g9_science_l1', 'essay', 3, 'فسّر أهمية حزام الأمان في السيارة اعتمادًا على قانون نيوتن الأول.', null, null, null, null, null, null, null, 'عند التوقف المفاجئ يستمر جسم الراكب في الحركة للأمام بسبب القصور الذاتي، فيؤثر حزام الأمان بقوة توقفه وتمنعه من الاصطدام بالزجاج أو المقعد الأمامي.', null, 5) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g9_science_l2', 'g9_science_u1', 'قانون نيوتن الثاني', array['أنص على قانون نيوتن الثاني.','أحسب القوة والكتلة والتسارع باستخدام العلاقة ق = ك × ت.']::text[], 'ينص قانون نيوتن الثاني على أن: تسارع الجسم يتناسب طرديًا مع القوة المحصلة المؤثرة فيه، وعكسيًا مع كتلته، ويكون في اتجاه القوة المحصلة.
الصيغة الرياضية: ق = ك × ت
• ق: القوة المحصلة وتقاس بالنيوتن (N).
• ك: الكتلة وتقاس بالكيلوغرام (kg).
• ت: التسارع ويقاس بالمتر لكل ثانية مربعة (m/s²).
النيوتن الواحد هو القوة التي تكسب جسمًا كتلته 1 kg تسارعًا مقداره 1 m/s².', array['جسم كتلته 2 kg يتسارع بمقدار 3 m/s²: ق = 2 × 3 = 6 N.','قوة محصلة 20 N تؤثر في جسم كتلته 5 kg: ت = 20 ÷ 5 = 4 m/s².']::text[], array['ق = ك × ت.','زيادة القوة تزيد التسارع.','زيادة الكتلة تقلل التسارع (للقوة نفسها).','وحدة القوة: النيوتن N = kg·m/s².']::text[], 'التسارع يزداد بزيادة القوة المحصلة ويقل بزيادة الكتلة، والعلاقة ق = ك × ت.', null, 5, 1, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l2_q1', 'g9_science_l2', 'numeric', 1, 'جسم كتلته 2 kg يتحرك بتسارع 3 m/s². ما مقدار القوة المحصلة المؤثرة فيه بالنيوتن؟', null, '6'::jsonb, null, null, 0.001, 'N', 'ق = ك × ت = 2 × 3 = 6 N.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l2_q2', 'g9_science_l2', 'mcq', 1, 'ما وحدة قياس القوة؟', array['الجول','النيوتن','الواط','الكيلوغرام']::text[], '1'::jsonb, null, null, null, null, 'تقاس القوة بالنيوتن.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l2_q3', 'g9_science_l2', 'numeric', 2, 'قوة محصلة مقدارها 20 N تؤثر في جسم كتلته 5 kg. ما تسارعه؟', null, '4'::jsonb, null, null, 0.001, 'm/s²', 'ت = ق ÷ ك = 20 ÷ 5 = 4 m/s².', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l2_q4', 'g9_science_l2', 'trueFalse', 2, 'إذا ضاعفنا كتلة الجسم مع بقاء القوة ثابتة فإن تسارعه يتضاعف.', null, 'false'::jsonb, null, null, null, null, 'التسارع يتناسب عكسيًا مع الكتلة، فيقل إلى النصف.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l2_q5', 'g9_science_l2', 'match', 2, 'صِل كل كمية بوحدة قياسها:', null, null, null, '[["القوة", "N"], ["الكتلة", "kg"], ["التسارع", "m/s²"]]'::jsonb, null, null, 'القوة بالنيوتن، والكتلة بالكيلوغرام، والتسارع بـ m/s².', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l2_q6', 'g9_science_l2', 'numeric', 3, 'ما كتلة جسم تكسبه قوة محصلة مقدارها 12 N تسارعًا قدره 4 m/s²؟', null, '3'::jsonb, null, null, 0.001, 'kg', 'ك = ق ÷ ت = 12 ÷ 4 = 3 kg.', null, null, 5) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_science_l2_q7', 'g9_science_l2', 'numeric', 4, 'دُفعت عربة كتلتها 10 kg بقوة 50 N، وكانت قوة الاحتكاك 20 N. ما تسارع العربة؟', null, '3'::jsonb, null, null, 0.001, 'm/s²', 'القوة المحصلة = 50 − 20 = 30 N، ت = 30 ÷ 10 = 3 m/s².', null, null, 6) on conflict (id) do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_science_book', 1, 'كتاب العلوم – الصف التاسع (نسخة تجريبية)

المحتويات:
• الوحدة الأولى: القوة والحركة', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_science_book', 2, 'الوحدة الأولى: القوة والحركة', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_science_book', 3, 'قانون نيوتن الأول (القصور الذاتي)

ينص قانون نيوتن الأول على أن: الجسم الساكن يبقى ساكنًا، والجسم المتحرك يبقى متحركًا بسرعة ثابتة وفي خط مستقيم، ما لم تؤثر فيه قوة محصلة تغيّر حالته.
تسمى ممانعة الجسم لتغيير حالته الحركية «القصور الذاتي»، ويزداد القصور الذاتي بزيادة كتلة الجسم.
لذلك يندفع الركاب إلى الأمام عند توقف الحافلة فجأة، ولهذا نستخدم حزام الأمان.', 'g9_science_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_science_book', 4, 'أمثلة محلولة:
• عند توقف السيارة فجأة يندفع جسم الراكب إلى الأمام لأنه يميل إلى الاستمرار في حركته.
• سحب مفرش الطاولة بسرعة يبقي الأطباق في مكانها تقريبًا بسبب قصورها الذاتي.

أتذكّر:
• لا يغيّر الجسم حالته الحركية إلا بقوة محصلة.
• القصور الذاتي يزداد بزيادة الكتلة.
• حزام الأمان تطبيق على القانون الأول.', 'g9_science_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_science_book', 5, 'قانون نيوتن الثاني

ينص قانون نيوتن الثاني على أن: تسارع الجسم يتناسب طرديًا مع القوة المحصلة المؤثرة فيه، وعكسيًا مع كتلته، ويكون في اتجاه القوة المحصلة.
الصيغة الرياضية: ق = ك × ت
• ق: القوة المحصلة وتقاس بالنيوتن (N).
• ك: الكتلة وتقاس بالكيلوغرام (kg).
• ت: التسارع ويقاس بالمتر لكل ثانية مربعة (m/s²).
النيوتن الواحد هو القوة التي تكسب جسمًا كتلته 1 kg تسارعًا مقداره 1 m/s².', 'g9_science_l2') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_science_book', 6, 'أمثلة محلولة:
• جسم كتلته 2 kg يتسارع بمقدار 3 m/s²: ق = 2 × 3 = 6 N.
• قوة محصلة 20 N تؤثر في جسم كتلته 5 kg: ت = 20 ÷ 5 = 4 m/s².

أتذكّر:
• ق = ك × ت.
• زيادة القوة تزيد التسارع.
• زيادة الكتلة تقلل التسارع (للقوة نفسها).
• وحدة القوة: النيوتن N = kg·m/s².', 'g9_science_l2') on conflict do nothing;
insert into exams (id, subject_id, title, duration_minutes, question_count) values ('g9_science_exam1', 'g9_science', 'امتحان تجريبي – العلوم', 25, 10) on conflict (id) do nothing;
insert into books (id, subject_id, title, pdf_url) values ('g9_english_book', 'g9_english', 'English – Grade 9 (Demo)', null) on conflict (id) do nothing;
insert into units (id, subject_id, semester, title, sort) values ('g9_english_u1', 'g9_english', 1, 'Unit 1: Grammar', 0) on conflict (id) do nothing;
insert into lessons (id, unit_id, title, objectives, explanation, examples, key_points, summary, video_url, book_page, sort, published) values ('g9_english_l1', 'g9_english_u1', 'The Present Perfect', array['أستخدم زمن المضارع التام للتعبير عن تجارب وأحداث لها أثر في الحاضر.','أكوّن جملًا مثبتة ومنفية وأسئلة بالمضارع التام.']::text[], 'يتكون زمن المضارع التام (Present Perfect) من: have / has + التصريف الثالث للفعل (past participle).
• نستخدم has مع he / she / it، و have مع I / you / we / they.
• نستخدمه للحديث عن تجارب في الحياة دون تحديد الوقت: I have visited Jerusalem.
• ولأحداث بدأت في الماضي وما زالت مستمرة مع for و since: She has lived in Gaza since 2010.
• النفي: have not (haven''t) / has not (hasn''t). السؤال: Have you finished?', array['I have finished my homework. (أنهيت واجبي)','He has not seen the film yet.','Have you ever been to Jericho?']::text[], array['have/has + V3.','for + مدة، since + نقطة بداية.','ever / never / already / yet كلمات دالة.']::text[], 'Present Perfect = have/has + V3، ويعبر عن تجارب أو أحداث ماضية مرتبطة بالحاضر.', null, 3, 0, true) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_english_l1_q1', 'g9_english_l1', 'mcq', 1, 'She ___ finished her project.', array['have','has','is','did']::text[], '1'::jsonb, null, null, null, null, 'مع she نستخدم has.', null, null, 0) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_english_l1_q2', 'g9_english_l1', 'mcq', 1, 'Choose the past participle of «write».', array['wrote','writed','written','writing']::text[], '2'::jsonb, null, null, null, null, 'write – wrote – written.', null, null, 1) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_english_l1_q3', 'g9_english_l1', 'fill', 2, 'They have lived here ___ 2015. (for / since)', null, null, array['since']::text[], null, null, null, 'since مع نقطة بداية محددة.', null, null, 2) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_english_l1_q4', 'g9_english_l1', 'fill', 2, 'I have studied English ___ six years. (for / since)', null, null, array['for']::text[], null, null, null, 'for مع مدة زمنية.', null, null, 3) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_english_l1_q5', 'g9_english_l1', 'trueFalse', 2, '«He have eaten breakfast» is a correct sentence.', null, 'false'::jsonb, null, null, null, null, 'الصحيح: He has eaten breakfast.', null, null, 4) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_english_l1_q6', 'g9_english_l1', 'short', 3, 'Make it negative: «We have seen this film.»', null, null, array['We have not seen this film.','We haven''t seen this film.','We have not seen this film','We haven''t seen this film']::text[], null, null, null, 'نضيف not بعد have.', null, null, 5) on conflict (id) do nothing;
insert into questions (id, lesson_id, type, difficulty, prompt, options, answer, accepted, pairs, tolerance, unit, explanation, model_answer, image, sort) values ('g9_english_l1_q7', 'g9_english_l1', 'essay', 3, 'Write two sentences about things you have done this year.', null, null, null, null, null, null, null, 'Example: I have read three books this year. I have helped my brother with his homework.', null, 6) on conflict (id) do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_english_book', 1, 'English – Grade 9 (Demo)

المحتويات:
• Unit 1: Grammar', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_english_book', 2, 'Unit 1: Grammar', null) on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_english_book', 3, 'The Present Perfect

يتكون زمن المضارع التام (Present Perfect) من: have / has + التصريف الثالث للفعل (past participle).
• نستخدم has مع he / she / it، و have مع I / you / we / they.
• نستخدمه للحديث عن تجارب في الحياة دون تحديد الوقت: I have visited Jerusalem.
• ولأحداث بدأت في الماضي وما زالت مستمرة مع for و since: She has lived in Gaza since 2010.
• النفي: have not (haven''t) / has not (hasn''t). السؤال: Have you finished?', 'g9_english_l1') on conflict do nothing;
insert into book_pages (book_id, number, text, lesson_id) values ('g9_english_book', 4, 'أمثلة محلولة:
• I have finished my homework. (أنهيت واجبي)
• He has not seen the film yet.
• Have you ever been to Jericho?

أتذكّر:
• have/has + V3.
• for + مدة، since + نقطة بداية.
• ever / never / already / yet كلمات دالة.', 'g9_english_l1') on conflict do nothing;
commit;
